Don't use `servo/rust-url` crate
`url` crate isn't published on crates.io. Thus if one wants to publish a create which depends on `url`, an error  occurs:
```
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: all dependencies must come from the same source.
dependency `url` comes from https://github.com/servo/rust-url instead
```
This commit is a workaround: http_event_store uses String instead of url::Url.